{% set name = "scikit-datasets" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-datasets-{{ version }}.tar.gz
  sha256: 47663e4c9d9edcae0e1ea8759c8e8485e282fc615d4f341665f0ba657675ba9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - scikit-learn
    - scipy

test:
  imports:
    - skdatasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/daviddiazvico/scikit-datasets
  summary: Scikit-learn-compatible datasets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnmabus
